# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace # Trims trailing whitespace.
        args: [--markdown-linebreak-ext=md]
      - id: check-ast # Checks whether the files parse as valid python.
      - id: check-case-conflict # Checks for files that would conflict in case-insensitive filesystems.
      - id: check-json # Attempts to load all json files to verify syntax
      - id: check-merge-conflict # Check for files that contain merge conflict strings
      - id: check-xml # Attempts to load all xml files to verify syntax
      - id: check-toml # Attempts to load all toml files to verify syntax
      - id: check-yaml # Attempts to load all yaml files to verify syntax
      - id: check-yaml # Attempts to load all yaml files to verify syntax
        args: [--unsafe]
      - id: end-of-file-fixer # Makes sure files end in a newline and only a newline.
      - id: check-symlinks # Checks for symlinks which do not point to anything
        stages: [commit]
      - id: check-added-large-files # Prevent giant files from being committed
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
        args: [ --disable=MD013, --disable=MD002,--disable=MD032,--disable=MD005,--disable=MD009 ]
